### ISSUE TITLE
TypeError: Image is not a function on Chrome 42

### ISSUE THREAD

**Issue by byrne-yan** [ccorcos/meteor-clientside-image-manipulation#10]
TypeError: Image is not a function
    at processImage (ccorcos_clientside-image-manipulation.js:958)

**Comment by byrne-yan** [comment]
```
  canvas = document.createElement('canvas');                                                // 956
  ctx = canvas.getContext("2d");                                                            // 957
  img = new Image();                                                                        // 958
  url = (window.URL ? window.URL : window.webkitURL);                                       // 959
  img.src = url.createObjectURL(imageFile);                                                 // 960
  return img.onload = function(e) {             
```

**Comment by ccorcos** [comment]
You probably redefined `Image` to be something else. Its a native object. Open up your console on this webpage and try it.

**Comment by byrne-yan** [comment]
The issue found on meteor android with crosswalk. 
![image](https://cloud.githubusercontent.com/assets/9878971/9835540/197e9c30-5a23-11e5-8cf6-0b6cf047f68a.png)

**Comment by byrne-yan** [comment]
Image() constructor is just a recommendation for HTML5 W3C. Is there any workaround on browser that don't support Image()?

**Comment by byrne-yan** [comment]
Solved. It is caused by one of my meteor package which exports Image. Thanks for your tips!

**Comment by ccorcos** [comment]
Haha well there you go!
