### ISSUE TITLE
Only Do Orientation

### ISSUE THREAD

**Issue by digilord** [ccorcos/meteor-clientside-image-manipulation#2]
Is it possible to ONLY do orientation correction with your library?

**Comment by ccorcos** [comment]
although kind of a hack, you could just pass in huge values for maxWidth and maxHeight.

https://github.com/ccorcos/meteor-clientside-image-manipulation/blob/master/lib/processImage.coffee#L41

It would be a good idea to make maxWidth and maxHeight optional parameters.

**Comment by ccorcos** [comment]
There you go brutha.

https://github.com/ccorcos/meteor-clientside-image-manipulation/commit/973a8d684b5ed446f5bf6c3c933486323b33ef9b
