### ISSUE TITLE
Green screen effect

### ISSUE THREAD

**Issue by danecando** [ccorcos/meteor-clientside-image-manipulation#4]
Not familiar with manipulating images with canvas but it seems that it causes a sort of 'green screen effect'. Where green ends up coming out transparent or white. 

Is this a known thing or some kind of odd bug that I'm experiencing ?

**Comment by ccorcos** [comment]
I have no idea what youre talking about

**Comment by danecando** [comment]
For example if you resized this image: http://1.bp.blogspot.com/-mXw63W01tGA/VGprSrCpYFI/AAAAAAAABU8/Z4fAycJNd4o/s1600/B2rIjcsIEAABK5_.jpg

It would come out with a transparent background

**Comment by ccorcos** [comment]
whoa. you're right.... wtf?!

**Comment by ccorcos** [comment]
lol. wherever I found the resizing code from, they must have also been filtering out a green screen as well hahaha

https://github.com/ccorcos/meteor-clientside-image-manipulation/commit/59ed8d45b18b8369be131f60d13d84b2e41543d2

**Comment by danecando** [comment]
haha nice thanks man
